package cn.tom;

import cn.tom.dao.ClzDao;
import cn.tom.dao.UserDao;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SbDemo1Application {

    public static void main(String[] args) {
        //Application 应用  Context 背景
        // ioc 变量就是获取 Map
        ApplicationContext ioc =
                SpringApplication.run(SbDemo1Application.class, args);
        //Bean 豆子， IOC 容器保存的对象称之为 Bean
        System.out.println("如下代码用来学习理解的用的");
        System.out.println("===========按照 ID 来取 Bean==================");
        Object userDao = ioc.getBean("userDao");
        System.out.println("userDao=" + userDao);
        Object clzDao = ioc.getBean("clzDao");
        System.out.println("clzDao=" + clzDao);
        System.out.println("===========按照 类型 来取 Bean==================");
        ClzDao clzDao1 = ioc.getBean(ClzDao.class);
        clzDao1.add();
        UserDao userDao1 = ioc.getBean(UserDao.class);
        userDao1.add();
    }

}
