package com.example.demo;

import com.example.demo.dao.UserDao;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        //Application应用 Context背景
        //ioc变量就是获取map
        ApplicationContext ioc = SpringApplication.run(DemoApplication.class,args);
        System.out.println("如下代码测试学习用");
                //Bean 豆子，ioc容器保存的对象称之为Bean
//        Object clzDao = ioc.getBean("clzDao");
//        Object userDao = ioc.getBean("userDao");
//        System.out.println("userDao:" + clzDao);
//        System.out.println("按照类型来取");
//        UserDao clzDao1 = ioc.getBean(UserDao.class);
//        clzDao1.add();

    }
}
