package cn.tom;

import cn.tom.dao.ClzDao;
import cn.tom.dao.CourseDao;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Myb1Application {

    public static void main(String[] args) {

        ConfigurableApplicationContext ioc = SpringApplication.run(Myb1Application.class, args);

        CourseDao courseDao = ioc.getBean(CourseDao.class);

        System.out.println(courseDao);


    }
}
